#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import InstancesHandler, CoapError
from kubernetes import config, client

class InstancesHandler_33627(InstancesHandler):
    EXTERNAL_NOTIFY = False

    def create(self,
               instance_id):  # int
        # TODO: create new instance
        raise CoapError.NOT_IMPLEMENTED

    def delete(self,
               instance_id):  # int
        # TODO: delete instance
        # TODO: raise CoapError.BAD_REQUEST if instance does not exist
        raise CoapError.NOT_IMPLEMENTED

    def list(self):
        config.load_kube_config()
        v1 = client.CoreV1Api()
        pods = v1.list_namespaced_pod("default", watch=False)
        nums = [str(i) for i in range(len(pods.items))]
        print(" ".join(nums))


if __name__ == '__main__':
    InstancesHandler_33627().main()
