#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
from kubernetes import client, config

class ResourceHandler_33627_1(ResourceHandler):
    NAME = "Ready containers"
    DESCRIPTION = '''\
Number of ready containers.'''
    DATATYPE = DataType.INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        config.load_kube_config()
        v1 = client.CoreV1Api()
        pods = v1.list_namespaced_pod(namespace="default", watch=False)
        statuses = pods.items[instance_id].status.container_statuses
        ready = list(filter(lambda x: x.ready, statuses))
        print(len(ready))




if __name__ == '__main__':
    ResourceHandler_33627_1().main()
