#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_33627_10(ResourceHandler):
    NAME = "Node"
    DESCRIPTION = '''\
Link to object instance of the node on which the pod is running.'''
    DATATYPE = DataType.OBJECT LINK
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: print value to stdout
        print(None)




if __name__ == '__main__':
    ResourceHandler_33627_10().main()
