#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
from kubernetes import client, config

class ResourceHandler_33627_10(ResourceHandler):
    NAME = "Node"
    DESCRIPTION = '''\
Link to object instance of the node on which the pod is running.'''
    DATATYPE = DataType.OBJLNK
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        config.load_kube_config()
        v1 = client.CoreV1Api()
        pods = v1.list_namespaced_pod(namespace="default", watch=False)
        nodes = v1.list_node(watch=False).items
        node_names = [node.metadata.name for node in nodes]
        idx = node_names.index(pods.items[instance_id].spec.node_name)
        print(f'/33626/{idx}')




if __name__ == '__main__':
    ResourceHandler_33627_10().main()
