#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
from kubernetes import client, config

class ResourceHandler_33627_11(ResourceHandler):
    NAME = "Delete"
    DESCRIPTION = '''\
Delete the pod.'''

    def execute(self,
                instance_id,  # int
                args):        # int -> (str or None)
        config.load_kube_config()
        v1 = client.CoreV1Api()
        pods = v1.list_namespaced_pod(namespace="default", watch=False)
        name = pods.items[instance_id].metadata.name
        v1.delete_namespaced_pod(name=name, namespace="default")



if __name__ == '__main__':
    ResourceHandler_33627_11().main()
