#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
from kubernetes import client, config

class ResourceHandler_33627_2(ResourceHandler):
    NAME = "Total containers"
    DESCRIPTION = '''\
Number of total containers.'''
    DATATYPE = DataType.INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        config.load_kube_config()
        v1 = client.CoreV1Api()
        pods = v1.list_namespaced_pod(namespace="default", watch=False)
        containers = pods.items[instance_id].spec.containers
        print(len(containers))




if __name__ == '__main__':
    ResourceHandler_33627_2().main()
