#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
from kubernetes import client, config
from datetime import datetime

class ResourceHandler_33627_3(ResourceHandler):
    NAME = "Age"
    DESCRIPTION = '''\
Age of the pod.'''
    DATATYPE = DataType.STRING
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        config.load_kube_config()
        v1 = client.CoreV1Api()
        pods = v1.list_namespaced_pod(namespace="default", watch=False)
        timestamp = pods.items[instance_id].status.start_time
        date = datetime.strptime(timestamp, '%Y-%m-%dT%H:%M:%S.%f')
        print(str(date - datetime.now()))




if __name__ == '__main__':
    ResourceHandler_33627_3().main()
