#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_33627_4(ResourceHandler):
    NAME = "Phase"
    DESCRIPTION = '''\
Current phase of the node: 1 - Pending 2 - Running 3 - Succeeded 4 -
 * Failed 5 - Unknown'''
    DATATYPE = DataType.UNSIGNED_INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: print value to stdout
        print(None)




if __name__ == '__main__':
    ResourceHandler_33627_4().main()
