#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
from kubernetes import client, config

class ResourceHandler_33627_4(ResourceHandler):
    NAME = "Phase"
    DESCRIPTION = '''\
Current phase of the pod: 1 - Pending 2 - Running 3 - Succeeded 4 -
 * Failed 5 - Unknown'''
    DATATYPE = DataType.UNSIGNED_INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        phase_nums = {
            'Pending': 1,
            'Running': 2,
            'Succeeded': 3,
            'Failed': 4,
            'Unknown': 5,
        }

        config.load_kube_config()
        v1 = client.CoreV1Api()
        pods = v1.list_namespaced_pod(namespace="default", watch=False)
        phase = pods.items[instance_id].status.phase
        print(phase_nums[phase])




if __name__ == '__main__':
    ResourceHandler_33627_4().main()
