#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_33627_5(ResourceHandler):
    NAME = "Condition"
    DESCRIPTION = '''\
Current condition of the node: 1 - PodScheduled 2 - PodHasNetwork 3 -
 * ContainersReady 4 - Initialized 5 - Ready'''
    DATATYPE = DataType.UNSIGNED INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: print value to stdout
        print(None)




if __name__ == '__main__':
    ResourceHandler_33627_5().main()
