#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
from kubernetes import client, config

class ResourceHandler_33627_5(ResourceHandler):
    NAME = "Condition"
    DESCRIPTION = '''\
Current condition of the pod: 1 - PodScheduled 2 - PodHasNetwork 3 -
 * ContainersReady 4 - Initialized 5 - Ready'''
    DATATYPE = DataType.INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        cond_nums = {
            'PodScheduled': 1,
            'PodHasNetwork': 2,
            'ContainersReady': 3,
            'Initialized': 4,
            'Ready': 5,
        }

        config.load_kube_config()
        v1 = client.CoreV1Api()
        pods = v1.list_namespaced_pod(namespace="default", watch=False)
        cond = 0
        for condition in pods.items[instance_id].status.conditions:
            if condition.status == 'True':
                cond = cond_nums[condition.type]
        print(cond)




if __name__ == '__main__':
    ResourceHandler_33627_5().main()
