#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
from kubernetes import client, config

class ResourceHandler_33627_6(ResourceHandler):
    NAME = "Restarts"
    DESCRIPTION = '''\
Number of restarts of the pod.'''
    DATATYPE = DataType.INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        config.load_kube_config()
        v1 = client.CoreV1Api()
        pods = v1.list_namespaced_pod(namespace="default", watch=False)
        restarts = 0
        for condition in pods.items[instance_id].status.container_statuses:
            restarts += condition.restart_count
        print(restarts)




if __name__ == '__main__':
    ResourceHandler_33627_6().main()
