#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
from kubernetes import client, config

class ResourceHandler_33627_9(ResourceHandler):
    NAME = "CPU usage"
    DESCRIPTION = '''\
Pod's CPU usage.'''
    DATATYPE = DataType.FLOAT
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        config.load_kube_config()
        v1 = client.CoreV1Api()
        pods = v1.list_namespaced_pod(namespace="default", watch=False)
        api = client.CustomObjectsApi()
        pods_stats = api.list_cluster_custom_object("metrics.k8s.io", "v1beta1", "pods")
        stats = list(filter(lambda x: x['metadata']['name'] == pods.items[instance_id].metadata.name, pods_stats['items']))[0]
        cpu_usage = 0
        for container in stats['containers']:
            cpu_usage += int(container['usage']['cpu'].split('n')[0]) / 1000000
        print(cpu_usage)




if __name__ == '__main__':
    ResourceHandler_33627_9().main()
