#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import InstancesHandler, CoapError


class InstancesHandler_33626(InstancesHandler):
    EXTERNAL_NOTIFY = False

    def create(self,
               instance_id):  # int
        # TODO: create new instance
        raise CoapError.NOT_IMPLEMENTED

    def delete(self,
               instance_id):  # int
        # TODO: delete instance
        # TODO: raise CoapError.BAD_REQUEST if instance does not exist
        raise CoapError.NOT_IMPLEMENTED

    def list(self):
        # TODO: print space-separated list of existing instances to stdout
        print("0")


if __name__ == '__main__':
    InstancesHandler_33626().main()
