#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import InstancesHandler, CoapError
import docker

class InstancesHandler_33628(InstancesHandler):
    EXTERNAL_NOTIFY = False

    def create(self,
               instance_id):  # int
        # TODO: create new instance
        raise CoapError.NOT_IMPLEMENTED

    def delete(self,
               instance_id):  # int
        # TODO: delete instance
        # TODO: raise CoapError.BAD_REQUEST if instance does not exist
        raise CoapError.NOT_IMPLEMENTED

    def list(self):
        client = docker.from_env()
        containers = client.containers.list()
        nums = [str(i) for i in range(len(containers))]
        print(" ".join(nums))


if __name__ == '__main__':
    InstancesHandler_33628().main()
