#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
import docker

class ResourceHandler_33628_0(ResourceHandler):
    NAME = "Container ID"
    DESCRIPTION = '''\
ID of the container.'''
    DATATYPE = DataType.STRING
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        client = docker.from_env()
        container = client.containers.list()[instance_id]
        print(container.id)




if __name__ == '__main__':
    ResourceHandler_33628_0().main()
