#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_33628_1(ResourceHandler):
    NAME = "Image"
    DESCRIPTION = '''\
Image from which the container was created.'''
    DATATYPE = DataType.STRING
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: print value to stdout
        print("TODO")




if __name__ == '__main__':
    ResourceHandler_33628_1().main()
