#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
import docker

class ResourceHandler_33628_3(ResourceHandler):
    NAME = "Created"
    DESCRIPTION = '''\
How long ago was the container created.'''
    DATATYPE = DataType.STRING
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        client = docker.from_env()
        container = client.containers.list()[instance_id]
        print(container.attrs['Created'])




if __name__ == '__main__':
    ResourceHandler_33628_3().main()
