#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
import docker

class ResourceHandler_33628_5(ResourceHandler):
    NAME = "Ports"
    DESCRIPTION = '''\
Ports and protocols used by the container.'''
    DATATYPE = DataType.STRING
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        client = docker.from_env()
        container = client.containers.list()[instance_id]
        print(list(container.attrs['Config']['ExposedPorts'].keys())[resource_instance_id])


    def list(self,
             instance_id):  # int
        client = docker.from_env()
        container = client.containers.list()[instance_id]
        ports = list(container.attrs['Config']['ExposedPorts'].keys())
        nums = [str(i) for i in range(len(ports))]
        print(" ".join(nums))


if __name__ == '__main__':
    ResourceHandler_33628_5().main()
