#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
import docker

class ResourceHandler_33628_6(ResourceHandler):
    NAME = "Names"
    DESCRIPTION = '''\
Names used by the container.'''
    DATATYPE = DataType.STRING
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        client = docker.from_env()
        container = client.containers.list()[instance_id]
        info = client.df()['Containers']
        container_info = list(filter(lambda x: x['Id'] == container.id, info))[0]
        print(container_info['Names'][resource_instance_id])


    def list(self,
             instance_id):  # int
        client = docker.from_env()
        container = client.containers.list()[instance_id]
        info = client.df()['Containers']
        container_info = list(filter(lambda x: x['Id'] == container.id, info))[0]
        nums = [str(i) for i in range(len(container_info['Names']))]
        print(" ".join(nums))


if __name__ == '__main__':
    ResourceHandler_33628_6().main()
