#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
import docker

class ResourceHandler_33628_8(ResourceHandler):
    NAME = "Stop"
    DESCRIPTION = '''\
Stop the running container.'''

    def execute(self,
                instance_id,  # int
                args):        # int -> (str or None)
        client = docker.from_env()
        container = client.containers.list()[instance_id]
        container.stop()



if __name__ == '__main__':
    ResourceHandler_33628_8().main()
