#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_33628_9(ResourceHandler):
    NAME = "Stop"
    DESCRIPTION = '''\
Stop the running container.'''

    def execute(self,
                instance_id,  # int
                args):        # int -> (str or None)
        # TODO: implement
        raise CoapError.NOT_IMPLEMENTED



if __name__ == '__main__':
    ResourceHandler_33628_9().main()
