#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
from kubernetes import client, config


class ResourceHandler_33625_0(ResourceHandler):
    NAME = "Nodes"
    DESCRIPTION = '''\
Number of nodes in the cluster.'''
    DATATYPE = DataType.INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        config.load_kube_config()
        v1 = client.CoreV1Api()
        nodes = v1.list_node(watch=False)
        print(len(nodes.items))




if __name__ == '__main__':
    ResourceHandler_33625_0().main()
