#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_33626_1(ResourceHandler):
    NAME = "Role"
    DESCRIPTION = '''\
Role of the node: 1 - master 2 - agent'''
    DATATYPE = DataType.UNSIGNED INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: print value to stdout
        print(None)




if __name__ == '__main__':
    ResourceHandler_33626_1().main()
