#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
from kubernetes import client, config

class ResourceHandler_33626_1(ResourceHandler):
    NAME = "Role"
    DESCRIPTION = '''\
Role of the node: 1 - master 2 - agent'''
    DATATYPE = DataType.INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        config.load_kube_config()
        v1 = client.CoreV1Api()
        nodes = v1.list_node(watch=False)
        if "node-role.kubernetes.io/master" in nodes.items[instance_id].metadata.labels:
            print(1)
        else:
            print(2)




if __name__ == '__main__':
    ResourceHandler_33626_1().main()
