#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
from datetime import datetime, timezone

from fsdm import ResourceHandler, CoapError, DataType, KvStore
from kubernetes import client, config

class ResourceHandler_33626_2(ResourceHandler):
    NAME = "Age"
    DESCRIPTION = '''\
Age of the node.'''
    DATATYPE = DataType.STRING
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        config.load_kube_config()
        v1 = client.CoreV1Api()
        nodes = v1.list_node(watch=False)
        timestamp = nodes.items[instance_id].metadata.creation_timestamp
        print(str(datetime.now(timezone.utc) - timestamp))




if __name__ == '__main__':
    ResourceHandler_33626_2().main()
