#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
from kubernetes import client, config

class ResourceHandler_33626_4(ResourceHandler):
    NAME = "Memory usage"
    DESCRIPTION = '''\
Node's memory usage.'''
    DATATYPE = DataType.FLOAT
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        config.load_kube_config()
        api = client.CustomObjectsApi()
        nodes_stats = api.list_cluster_custom_object("metrics.k8s.io", "v1beta1", "nodes")
        memory_usage = int(nodes_stats['items'][instance_id]['usage']['memory'].split('Ki')[0]) / 1024
        print(memory_usage)




if __name__ == '__main__':
    ResourceHandler_33626_4().main()
