#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_33626_5(ResourceHandler):
    NAME = "Memory usage"
    DESCRIPTION = '''\
Node's memory usage.'''
    DATATYPE = DataType.FLOAT
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: print value to stdout
        print(0.0)




if __name__ == '__main__':
    ResourceHandler_33626_5().main()
