#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
from kubernetes import client, config

class ResourceHandler_33626_6(ResourceHandler):
    NAME = "Number of pods"
    DESCRIPTION = '''\
Number of pods running on the node.'''
    DATATYPE = DataType.UNSIGNED_INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        config.load_kube_config()
        v1 = client.CoreV1Api()
        nodes = v1.list_node(watch=False)
        name = nodes.items[instance_id].metadata.name
        field_selector = 'spec.nodeName=' + name
        pods = v1.list_namespaced_pod(watch=False, field_selector=field_selector)
        print(len(pods.items))




if __name__ == '__main__':
    ResourceHandler_33626_6().main()
