#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
from kubernetes import client, config
from prometheus_api_client import PrometheusConnect
import os

class ResourceHandler_33626_7(ResourceHandler):
    NAME = "CPU Temperature"
    DESCRIPTION = '''\
Node's CPU temperature.'''
    DATATYPE = DataType.FLOAT
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        config.load_kube_config()
        v1 = client.CoreV1Api()
        nodes = v1.list_node(watch=False)
        name = nodes.items[instance_id].metadata.name
        prom = PrometheusConnect(url=os.getenv('PROM_URL'), disable_ssl=True)
        label_config = {'instance': name}
        metric = prom.get_current_metric_value(metric_name='node_hwmon_temp_celsius', label_config=label_config)
        print(metric[0].value)




if __name__ == '__main__':
    ResourceHandler_33626_7().main()
