#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_33626_7(ResourceHandler):
    NAME = "Number of pods"
    DESCRIPTION = '''\
Number of pods running on the node.'''
    DATATYPE = DataType.UNSIGNED INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: print value to stdout
        print(None)




if __name__ == '__main__':
    ResourceHandler_33626_7().main()
